### ISSUE TITLE
Structure visualization ?

### ISSUE THREAD

**Issue by shenscore** [MagiKoco/GEM#2]
Hi,
    I want to ask how to visualize the output data of GEM?
    Is there a tool?

Thanks!

**Comment by GuangxiangZhu** [comment]
You can try PyMOL, or other online visualization tools.

**Comment by shenscore** [comment]
Sorry, I'm not familiar with PyMOL.
Can you explain some more details ?

**Comment by GuangxiangZhu** [comment]
PyMOL is a open-source molecular visualization software, which is usually used for visualing 3D protein structures. There  are many online tutorials, such as [https://www.google.com/search?source=hp&ei=-_1KXJbXJoHT-Qau8J-oBA&q=pymol+tutorial&btnK=Google+%E6%90%9C%E7%B4%A2&oq=py&gs_l=psy-ab.3.1.35i39l2j0l8.1326.2803..4215...1.0..0.306.1207.2-2j2....3..0....1..gws-wiz.....0.v-BQfArVxJU](url) . 

The attachment files 1.pdb-4.pdb are that we used in PyMOL, and conf.pse and ens.pse  are the final PyMOL session files that produce the png files for Figure 3A. You can check these files to learn about the format setting and PyMOL configuration. In addition, I have just written a simple matlab script (plot3dr.m) to help you convert to PDB. Maybe it needs some slight modification to obtain better chromosome visualizations. 

Note that we use linear interpretation to allow PyMOL to draw the 'cartoon' style which is a more smooth style than 'sticks' and 'lines' and needs intermediate nodes for plotting. Of course, you can remove the interpolated points and use the  'sticks' and 'lines' style. Maybe other visualizations tools specialized for genome can provide smooth styles ( similar to 'cartoon'  ) which do not require intermediate nodes for plotting. By the way, there may be other modern tools for genome visualization and you can try them (PyMOL is only powerful for visualizing protein structure and hard-to-use for genome).

If you are not familiar with these visualization tools, you can use plot3 in MATLAB for a simple display ([https://www.mathworks.com/help/matlab/ref/plot3.html](url)).


[figure3a.zip](https://github.com/MagiKoco/GEM/files/2796022/figure3a.zip)
